function Ephem_Data = readEphemData(filename, dataLines)
%IMPORTFILE Import ephemeris data from provided text files
%  EPHEM_DATA = readEphemData(FILENAME) reads ephemeris data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  EPHEM_DATA = readEphemData(FILE, DATALINES) reads ephemeris data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  earthData = readEphemdata("C:\Users\ianmf\OneDrive\Documents\MATLAB\ASEN5050\HW6\HW6_Ephem_Earth.txt", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Oct-2024 14:49:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["JDTDB", "CalendarDateTDB", "X", "Y", "Z", "VX", "VY", "VZ"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "CalendarDateTDB", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "CalendarDateTDB", "EmptyFieldRule", "auto");

% Import the data
Ephem_Data = readtable(filename, opts);

end